CREATE DATABASE OBD;
USE OBD

CREATE TABLE Vehicle
(
  ID_Vehicle INT NOT NULL,
  Name VARCHAR(50) NOT NULL,
  Address VARCHAR(255) NOT NULL,
  SetUpTime DATE NOT NULL,
  CorrectionTime DATE NOT NULL,
  Phone CHAR NOT NULL,
  Location VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID_Vehicle)
);

CREATE TABLE User
(
  Name VARCHAR(50) NOT NULL,
  Password VARCHAR(200) NOT NULL,
  Role INT NOT NULL,
  Address VARCHAR(255) NOT NULL,
  PRIMARY KEY (Name)
);

CREATE TABLE SetUp
(
  SetUp_ID INT NOT NULL,
  S1 FLOAT,
  S2 FLOAT,
  S3 FLOAT,
  S4 FLOAT,
  S5 FLOAT,
  S6 FLOAT,
  S7 FLOAT,
  S8 FLOAT,
  S9 FLOAT,
  S10 FLOAT,
  S11 FLOAT,
  S12 FLOAT,
  S13 FLOAT,
  S14 FLOAT,
  S15 FLOAT,
  S16 FLOAT,
  S17 FLOAT,
  S18 FLOAT,
  S19 FLOAT,
  S20 FLOAT,
  S21 FLOAT,
  S22 FLOAT,
  S23 FLOAT,
  S24 FLOAT,
  S25 FLOAT,
  S26 FLOAT,
  S27 FLOAT,
  S28 FLOAT,
  S29 FLOAT,
  S30 FLOAT,
  ID_Vehicle INT NOT NULL,
  PRIMARY KEY (SetUp_ID),
  FOREIGN KEY (ID_Vehicle) REFERENCES Vehicle(ID_Vehicle)
);

CREATE TABLE Handle
(
  Name VARCHAR(50) NOT NULL,
  ID_Vehicle INT NOT NULL,
  PRIMARY KEY (Name, ID_Vehicle),
  FOREIGN KEY (Name) REFERENCES User(Name),
  FOREIGN KEY (ID_Vehicle) REFERENCES Vehicle(ID_Vehicle)
);

CREATE TABLE Data
(
  Data_ID INT NOT NULL,
  Time DATE NOT NULL,
  S1 FLOAT,
  S2 FLOAT,
  S3 FLOAT,
  S4 FLOAT,
  S5 FLOAT,
  S6 FLOAT,
  S7 FLOAT,
  S8 FLOAT,
  S9 FLOAT,
  S10 FLOAT,
  S11 FLOAT,
  S12 FLOAT,
  S13 FLOAT,
  S14 FLOAT,
  S15 FLOAT,
  S16 FLOAT,
  S17 FLOAT,
  S18 FLOAT,
  S19 FLOAT,
  S20 FLOAT,
  S21 FLOAT,
  S22 FLOAT,
  S23 FLOAT,
  S24 FLOAT,
  S25 FLOAT,
  S26 FLOAT,
  S27 FLOAT,
  S28 FLOAT,
  S29 FLOAT,
  S30 FLOAT,
  ID_Vehicle INT NOT NULL,
  PRIMARY KEY (Data_ID),
  FOREIGN KEY (ID_Vehicle) REFERENCES Vehicle(ID_Vehicle)
);